services:
  # api-dev:
  #   depends_on: [db-dev]
  #   env_file: ".env.development"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   container_name: mandali_api_dev
  #   #restart: always
  #   ports:
  #     - 3111:3111
  #   develop:
  #     watch:
  #       - action: rebuild
  #         path: package.json
  #       - action: sync
  #         path: ./src
  #         target: /usr/src/app/src
  #         ignore: [node_modules]
  #   networks:
  #     - network-dev

  cache:
    env_file: ".env.development"
    container_name: mandali_cache_dev
    image: redis
    restart: always
    ports:
      - 6380:6379
    networks:
      - network-dev

  db-dev:
    env_file: ".env.development"
    container_name: mandali_db_dev
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5434:5432
    networks:
      - network-dev

networks:
  network-dev:
    driver: bridge